### ISSUE TITLE
Cart Context solution might need more optimization via best practices

### ISSUE THREAD

**Issue by ryan-zayne** [jemmycodes/jemmy-foods#1]
@jemmycodes, tbh loving the file structure you've got going on here 👌

But on the other hand, I do believe the cart context provider might need a bit more work if truly you've chosen to stick with context api as your global state solution.

First let's start with the first line which might be problematic in terms of performance going forward 👇:

` 
<Provider value={{ cart, addToCart, removeFromCart, reduceFromCart }}>
`

Purely for the sake of fun in learning, I'd leave you to just as well try finding out what exactly could be perf issue there.

I trust you'd definitely come up with something profound, and then maybe on a later date we could discuss all about context, whilst looking at it's various pros as well as cons as a state solution. And finally maybe some optimzation tricks as well.

Till then tho, good job so far👍

**Comment by jemmycodes** [comment]
Yeahh!! Thank you so much. Sometimes while coding, bad code might creep in😂😂.

 The object being passed to the value prop there would be created after every render I guess, which is quite a hit on performance. Though, I might argue it's relatively insignificant and doesn't cost anything but it could be written in a better way.

Probably I'll create the object and memoize it with the `useMemo()` hook since I can't create the object outside jsx because it can't accept those functions since they're not scoped globally🤔💭

I'll appreciate if you have a better idea 💡☺️

**Comment by ryan-zayne** [comment]
Yes! You're definitely on to something.

The object would be created every render and as you rightly said, it may or may not cause a big hit in performance.
But you never truly know which component might consume that context, and in cases where that said component is computationally heavy, performance might become quite an issue.

So yeah, useMemo is definitely the right way to go in the scenario

Cheers 🥂

**Comment by ryan-zayne** [comment]
Another thing tho, you might also want to wrap those functions in useCallback as well, because if you don't, and you add those functions as dependencies to the useMemo hook (as Eslint would make you do), it will render the memoization partially useless since those functions will keep getting recreated on every render

**Comment by jemmycodes** [comment]
> Another thing tho, you might also want to wrap those functions in useCallback as well, because if you don't, and you add those functions as dependencies to the useMemo hook (as Eslint would make you do), it will render the memoization partially useless since those functions will keep getting recreated on every render 

Now this is the issue I have with react and it's performance icks🥲😂. Having to manage everything manually and telling them when to run and when not to sigh.

Thank you for the suggestions. I'll work on all this in my next commit!❤️💡

**Comment by ryan-zayne** [comment]
> Now this is the issue I have with react and it's performance icks🥲😂. Having to manage everything manually and telling them when to run and when not to sigh.
>

You definitely ain't alone in that😂
Cheers nevertheless 🥂
